# Generated by Django 6.1 on 2026-08-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quentity',
            new_name='quantity',
        ),
    ]
