# Generated by Django 6.1 on 2026-08-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_card_depositrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositrequest',
            old_name='amout',
            new_name='amount',
        ),
    ]
