# Generated by Django 6.1 on 2026-08-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_amout_depositrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda (Admin tasdiqlanishi kutilmoqda)'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=15, verbose_name='Status'),
        ),
    ]
